services:
  parrot-ctf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parrot-ctf
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./results:/results
    network_mode: bridge
    stdin_open: true
    tty: true

